### ISSUE TITLE
Crash when trying to view recipe in JEI/NEI

### ISSUE THREAD

**Issue by brisingraerowing** [hanakocz/RailCraft-Cosmetic-Additions-2#3]
I am using JEI (with the new version of NEI on top of it), and I tried to view the recipe for the Tanker Cart (I think), and the game froze then crashed with the following log:

[Crash Log](https://gist.github.com/BrisingrAerowing/613d2caf6b790bc448f328ff9a0b108c)

Not quite sure what happened there.

**Comment by hanakocz** [comment]
Hi, 
is it really needed to use NEI, when you use JEI? 
However, it may be caused because of the recipe of Tank cart uses the block that is not available (it uses Railcraft glass side of multiblock tank, however that is not yet reimplemented at least in last public version). With only JEI there was no crash as I know. 
However, this thing is already solved in dev, I am taking care of all those recipes, see #1 . It will use alternate recipe when the block used won't be available. I will release the new version soon, I wanted to include some new features into next release, but will do one build without them still to fix the crash.

**Comment by brisingraerowing** [comment]
NEI for 1.8+ is a JEI plugin, actually. It just adds the features that JEI didn't take, like the custom items.

**Comment by hanakocz** [comment]
Should be fixed with new recipes in [new build](https://github.com/hanakocz/RailCraft-Cosmetic-Additions-2/commit/6807355feb1c0de6a9c154e5cc942b56899aed30) . Please check and report back if it is not, thanks @BrisingrAerowing
